# Generated by Django 4.2.30 on 2026-05-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
