# Generated by Django 6.0.6 on 2026-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_videodata_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='video_file',
            field=models.FileField(max_length=500, upload_to='videos/'),
        ),
    ]
